# Site settings
title: "Bluellama Programmer"
author: "Bluellama Programmer"
description: "This is a blog about software, some mathematics, and the occasional economics. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I'm software engineer with passion for various technologies and sciences. I have a great desire to contribute to the development of society. By paying attention not only to engineering but also to science, economy, society problems and so on. I find it a great pleasure to solve various problems through software engineering. Also, the pleasure is the driving force of my life. "
colophon: "This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://llamakoo.github.io/"

# twitter_username: ferreira_hugo
github_username: llamakoo
# linkedin_username: hugoserenoferreira
# facebook_username: hugo.sereno.ferreira
google-analytics: UA-160206678-1

email: llamakoo9@gmail.com
simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
future: true